version: "1"
services:
  jenkins:
      build:
        context: jenkins
        dockerfile: dockerfile
      volumes:
        - $PWD/jenkins/.stuff:/var/jenkins_home
        - $PWD/jenkins:/app
      ports:
        - 8080:8080
  aws:
    image: anigeo/awscli
    working_dir: /app
    volumes:
      - $PWD/:/app
    env_file: .env
  terraform:
    build:
      dockerfile: Dockerfile
      context: terraform
    env_file: .env
    volumes:
      - $PWD/terraform:/app
    working_dir: /app
  webapp:
    image: saravak/tomcat8
    ports:
      - "8081:8080"
  app1:
    build: ./app1
  app2:
    build: ./app2
