FROM jenkins/jenkins:alpine
MAINTAINER Alexander Kazimirskiy <alexander.kazimirsky@gmail.com>
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/plugins.txt
EXPOSE 8080