pipeline {
    agent any
    stages {
        stage('Build app') {
            steps {
                sh "scripts/build.sh"
            }
        }
        stage('Test app') {
            steps {
                sh "scripts/test.sh"
            }
        }
        stage('Deploy app') {
            steps {
                sh "scripts/deploy.sh"
            }
        }
    }
}